### ISSUE TITLE
Move authors collection to type: data

### ISSUE THREAD

**Issue by Serpentarius13** [jktrn/astro-erudite#4]
We can swap all authors records to json, since they are only used for their properties and not as pages. Also, it would be possible to use auto json schema generator like that to not miss out on any props:
```json
{
  "$schema": "../../../.astro/collections/authors.schema.json",
  "name": "Armand",
  "pronouns": "he/him"
}
```

**Comment by jktrn** [comment]
Hi! Thanks for opening an issue.

The reason why I kept it as an `.md` file is because later down the road we can add individual author profiles and render the body of the `.md` as their own profile page (e.g. in an "About Me" section).

**Comment by Serpentarius13** [comment]
> Hi! Thanks for opening an issue.
> 
> The reason why I kept it as an `.md` file is because later down the road we can add individual author profiles and render the body of the `.md` as their own profile page (e.g. in an "About Me" section).

Okay, got it!
