### ISSUE TITLE
Update to Astro 5.x

### ISSUE THREAD

**Issue by d53dave** [jktrn/astro-erudite#5]
Hi, 

because npm started reporting vulnerabilities, I tried to update to Astro 5.0.9, but failed.

Astro has deprecated (and blocked) the use of `astro:content` in client code, and the refactoring seems to be somewhat non-trivial (at least for me, not having a lot of experience with Astro), as documented here: https://5-0-0-beta--astro-docs-2.netlify.app/en/guides/upgrade-to/v5/#changed-astrocontent-can-no-longer-be-used-on-the-client

**Comment by jktrn** [comment]
Hey, sorry about this. I'll take a look soon.
